package com.howard.www.handle.bean;
/**
 * STRING:connection.client.user
 * HTTP.URI:request.referer
 * HTTP.PROTOCOL:request.referer.protocol
 * HTTP.USERINFO:request.referer.userinfo
 * HTTP.HOST:request.referer.host
 * HTTP.PORT:request.referer.port
 * HTTP.PATH:request.referer.path
 * HTTP.QUERYSTRING:request.referer.query
 * STRING:request.referer.query.*
 * HTTP.REF:request.referer.ref
 * TIME.STAMP:request.receive.time
 * TIME.DAY:request.receive.time.day
 * TIME.MONTHNAME:request.receive.time.monthname
 * TIME.MONTH:request.receive.time.month
 * TIME.WEEK:request.receive.time.weekofweekyear
 * TIME.YEAR:request.receive.time.weekyear
 * TIME.YEAR:request.receive.time.year
 * TIME.HOUR:request.receive.time.hour
 * TIME.MINUTE:request.receive.time.minute
 * TIME.SECOND:request.receive.time.second
 * TIME.MILLISECOND:request.receive.time.millisecond
 * TIME.MICROSECOND:request.receive.time.microsecond
 * TIME.NANOSECOND:request.receive.time.nanosecond
 * TIME.DATE:request.receive.time.date
 * TIME.TIME:request.receive.time.time
 * TIME.ZONE:request.receive.time.timezone
 * TIME.EPOCH:request.receive.time.epoch
 * TIME.DAY:request.receive.time.day_utc
 * TIME.MONTHNAME:request.receive.time.monthname_utc
 * TIME.MONTH:request.receive.time.month_utc
 * TIME.WEEK:request.receive.time.weekofweekyear_utc
 * TIME.YEAR:request.receive.time.weekyear_utc
 * TIME.YEAR:request.receive.time.year_utc
 * TIME.HOUR:request.receive.time.hour_utc
 * TIME.MINUTE:request.receive.time.minute_utc
 * TIME.SECOND:request.receive.time.second_utc
 * TIME.MILLISECOND:request.receive.time.millisecond_utc
 * TIME.MICROSECOND:request.receive.time.microsecond_utc
 * TIME.NANOSECOND:request.receive.time.nanosecond_utc
 * TIME.DATE:request.receive.time.date_utc
 * TIME.TIME:request.receive.time.time_utc
 * STRING:request.status.last
 * HTTP.USERAGENT:request.user-agent
 * HTTP.FIRSTLINE:request.firstline
 * HTTP.METHOD:request.firstline.method
 * HTTP.URI:request.firstline.uri
 * HTTP.PROTOCOL:request.firstline.uri.protocol
 * HTTP.USERINFO:request.firstline.uri.userinfo
 * HTTP.HOST:request.firstline.uri.host
 * HTTP.PORT:request.firstline.uri.port
 * HTTP.PATH:request.firstline.uri.path
 * HTTP.QUERYSTRING:request.firstline.uri.query
 * STRING:request.firstline.uri.query.*
 * HTTP.REF:request.firstline.uri.ref
 * HTTP.PROTOCOL_VERSION:request.firstline.protocol
 * HTTP.PROTOCOL:request.firstline.protocol
 * HTTP.PROTOCOL.VERSION:request.firstline.protocol.version
 * BYTES:response.body.bytes
 * BYTESCLF:response.body.bytes
 * IP:connection.client.host
 */